export const SET_CATEGORY = 'category/setCategory'

export const SET_LIST_TODO = 'listTodo/setListTodo'
export const SET_POST_TODO = 'postTodo/setPostTodo'
export const SET_UPDATE_TODO = 'updateTodo/setUpdateTodo'
export const SET_TODO_WORK = 'todoWork/setTodoWork'
export const SET_TODO_TRAVEL = 'todoWork/setTodoTravel'
export const SET_TODO_MUSIC = 'todoWork/setTodoMusic'
export const SET_TODO_STUDY = 'todoWork/setTodoStudy'
export const SET_TODO_HOME = 'todoWork/setTodoHome'
export const SET_TODO_SPORT = 'todoWork/setTodoSport'
export const SET_TODO_SHOPPING = 'todoWork/setTodoShopping'
